<?php
use Drupal\commerce_product\Entity\ProductType;
use Drupal\commerce_product\Entity\ProductVariationType;
use Drupal\Core\Entity\Display\EntityViewDisplayInterface;
use Drupal\Core\Entity\EntityInterface;
use Drupal\views\ViewExecutable;
use Drupal\Core\Access\AccessResult;
use Drupal\Core\Entity\EntityTypeInterface;
use Drupal\Core\Field\BaseFieldDefinition;
use Drupal\file\Entity\File;
use Drupal\image\Entity\ImageStyle;
use Drupal\Core\Url;
use Drupal\Component\Utility\Html;
use Drupal\Core\Template\Attribute;
use Drupal\domain_access\DomainAccessManagerInterface;
use Drupal\commerce_product\Entity\ProductVariation;
use Drupal\block_content\Entity\BlockContent;
use Drupal\Core\Session\AccountInterface;

/**
 * Implements hook_theme().
 */
function lesroidelareno_theme() {
  $hooks['views_view_render'] = [
    'preprocess functions' => [
      'template_preprocess_views_view_render'
    ],
    'render element' => 'element',
    'file' => 'lesroidelareno.theme.inc'
  ];
  return $hooks;
}

/**
 *
 * @param \Drupal\commerce_product\Entity\Product $product
 * @param string $operation
 * @param \Drupal\Core\Session\AccountInterface $account
 */
function lesroidelareno_commerce_product_variation_access(ProductVariation $product, $operation, AccountInterface $account) {
  //
  // dump($operation);
}

function lesroidelareno_preprocess_views_view__render(&$vars) {
  /**
   *
   * @var \Drupal\views\ViewExecutable $view
   */
  $view = $vars['view'];
  //
  $css = $view->display_handler->getOption('view_row_css');
  if ($css) {
    $Attribute = new Attribute();
    $css = explode(" ", $css);
    $Attribute->addClass($css);
    $vars['rows']['#attributes'] = $Attribute;
  }
  //
  $css = $view->display_handler->getOption('view_header_css');
  if ($css) {
    $Attribute = new Attribute();
    $css = explode(" ", $css);
    $Attribute->addClass($css);
    $vars['header']['#attributes'] = $Attribute;
  }
  //
  $css = $view->display_handler->getOption('view_form_css');
  if ($css) {
    $Attribute = new Attribute();
    $css = explode(" ", $css);
    $Attribute->addClass($css);
    if (!empty($vars['exposed']['#attributes']))
      $vars['exposed']['#attributes']->addClass($css);
    else
      $vars['exposed']['#attributes'] = $Attribute;
  }
  //
  $css = $view->display_handler->getOption('view_footer_css');
  if ($css) {
    $Attribute = new Attribute();
    $css = explode(" ", $css);
    $Attribute->addClass($css);
    $vars['footer']['#attributes'] = $Attribute;
  }
}

/**
 *
 * @param
 *        $vars
 */
function lesroidelareno_preprocess_html(&$vars) {
  $routeName = \Drupal::routeMatch()->getRouteName();
  // $parameters = \Drupal::routeMatch()->getParameters()->all();
  // if (!empty($parameters['content_generate_entity'])) {
  // /**
  // *
  // * @var \Drupal\generate_mapping_content\Entity\ContentGenerateEntity
  // $contentGenerate
  // */
  // $contentGenerate = $parameters['content_generate_entity'];
  // $intro = $contentGenerate->get('introduction')->value;
  // $metaDescription = [
  // '#tag' => 'meta',
  // '#attributes' => [
  // 'name' => 'description',
  // 'content' => strip_tags($intro)
  // ]
  // ];
  // $vars['page']['#attached']['html_head'][] = [
  // $metaDescription,
  // 'meta-description'
  // ];
  // }
  // else {
  // $vars['page']['#attached']['library'][] = 'login_rx_vuejs/vuejs_dev';
  // }
  //
  // On charge tawk sur les routes non admin.
  if (!str_contains($routeName, 'system.admin')) {
    $vars['page']['#attached']['library'][] = 'lesroidelareno/lesroidelareno_tawk.config';
  }
  //
  if ('entity.taxonomy_term.canonical' == $routeName) {
    if (empty($vars['page']['content']['attributes'])) {
      $Attribute = new Attribute();
      $Attribute->addClass('container');
      $vars['page']['content']['attributes'] = $Attribute;
    }
    else
      $vars['page']['content']['attributes']->addClass('container');
  }
}

function lesroidelareno_preprocess_facets_result_item__checkbox(&$vars) {
  
  // if (!empty($vars['items'])) {
  // foreach ($vars['items'] as $k => $item) {
  // $vars['items'][$k]['value']['#title']['icone'] = [
  // '#type' => 'html_tag',
  // '#tag' => 'h1',
  // '#value' => 'Icone'
  // ];
  // }
  // }
  $term = \Drupal::entityTypeManager()->getStorage('taxonomy_term')->loadByProperties([
    'name' => $vars['value'],
    'vid' => 'categorie_produit'
  ]);
  $image_style = 'thumbnail';
  /**
   *
   * @var \Drupal\taxonomy\Entity\Term $term
   */
  $field_name = 'field_image';
  $term = reset($term);
  if ($term->hasField($field_name)) {
    $first = $term->get($field_name)->first();
    if ($first) {
      $file = File::load($first->getValue()['target_id']);
      if ($file)
        $vars['icone'] = [
          '#theme' => 'image_style',
          '#style_name' => $image_style,
          '#uri' => $file->getFileUri()
        ];
    }
    else {
      $settings = $term->get($field_name)->getSettings();
      // dump($settings['default_image']);
      if (!empty($settings['default_image'])) {
        $fileManager = \Drupal::entityTypeManager()->getStorage('file');
        /**
         *
         * @var File $file
         */
        $file = $fileManager->loadByProperties([
          'uuid' => $settings['default_image']['uuid']
        ]);
        if (!empty($file)) {
          $file = reset($file);
          $vars['icone'] = [
            '#theme' => 'image_style',
            '#style_name' => $image_style,
            '#uri' => $file->getFileUri()
          ];
        }
      }
    }
  }
}

/**
 * Cette function est provisoir, elle corrige un bug au niveau de 'target_id';
 *
 * @param array $variables
 */
function lesroidelareno_preprocess_pager(array &$variables) {
  $element = $variables['pager']['#element'];
  $parameters = $variables['pager']['#parameters'];
  // $quantity = empty($variables['pager']['#quantity']) ? 0 :
  // $variables['pager']['#quantity'];
  $route_name = $variables['pager']['#route_name'];
  $route_parameters = $variables['pager']['#route_parameters'] ?? [];
  /** @var \Drupal\Core\Pager\PagerManagerInterface $pager_manager */
  // Drupal\Core\Pager\PagerManager
  $pager_manager = \Drupal::service('pager.manager');
  $pager = $pager_manager->getPager($element);
  if ($pager) {
    $current_page = $pager->getCurrentPage();
    $pager_max = $pager->getTotalPages();
    // clean parametter
    foreach ($parameters as $k => $value) {
      if (is_array($value)) {
        foreach ($value as $b => $val) {
          if (isset($val['target_id'])) {
            $parameters[$k][$b] = $val['target_id'];
          }
        }
      }
    }
    
    /**
     * On recrit les url pour les cas ou ces derniers contientienne target_id.
     */
    // pages
    if (!empty($variables['items']['pages'])) {
      foreach ($variables['items']['pages'] as $i => $page) {
        $options = [
          'query' => $pager_manager->getUpdatedParameters($parameters, $element, $i - 1)
        ];
        $variables['items']['pages'][$i]['href'] = Url::fromRoute($route_name, $route_parameters, $options)->toString();
      }
    }
    // first
    if (!empty($variables['items']['first'])) {
      $options = [
        'query' => $pager_manager->getUpdatedParameters($parameters, $element, 0)
      ];
      $variables['items']['first']['href'] = Url::fromRoute($route_name, $route_parameters, $options)->toString();
    }
    // previous
    if (!empty($variables['items']['previous'])) {
      $options = [
        'query' => $pager_manager->getUpdatedParameters($parameters, $element, $current_page - 1)
      ];
      $variables['items']['previous']['href'] = Url::fromRoute($route_name, $route_parameters, $options)->toString();
    }
    // Next
    if (!empty($variables['items']['next'])) {
      $options = [
        'query' => $pager_manager->getUpdatedParameters($parameters, $element, $current_page + 1)
      ];
      $variables['items']['next']['href'] = Url::fromRoute($route_name, $route_parameters, $options)->toString();
    }
    // last
    if (!empty($variables['items']['last'])) {
      $options = [
        'query' => $pager_manager->getUpdatedParameters($parameters, $element, $pager_max - 1)
      ];
      $variables['items']['last']['href'] = Url::fromRoute($route_name, $route_parameters, $options)->toString();
    }
  }
}

/**
 *
 * @file
 * Primary module hooks for lesroidelareno module.
 *
 * @DCG
 * This file is no longer required in Drupal 8.
 * @see https://www.drupal.org/node/2217931
 */
function lesroidelareno_views_pre_build(ViewExecutable $view) {
  /**
   *
   * @var \Drupal\node\Entity\Node $node
   */
  $node = \Drupal::routeMatch()->getParameter('node');
  if ($node) {
    if (!empty($node->field_selectionner_le_domaine) && $view->id() == 'realisations_par_prestataires') {
      /**
       *
       * @var \Drupal\Core\Field\FieldItemList $field
       */
      $field = $node->field_selectionner_le_domaine;
      $args = [];
      foreach ($field->getValue() as $val) {
        if (!empty($val['value'])) {
          $args[] = $val['value'];
          $args[] = $val['value'];
        }
      }
      
      $view->setArguments($args);
    }
    //
    elseif ($view->id() == 'produits_simialires' && $view->current_display == 'block_4') {
      /**
       *
       * @var \Drupal\Core\Field\FieldItemList $field
       */
      $field = $node->field_selectionner_le_domaine;
      $args = [];
      foreach ($field->getValue() as $val) {
        $args[] = $val['value'];
      }
      $view->setArguments($args);
    }
  }
}

/**
 * implement hook_preprocess_
 */
function lesroidelareno_preprocess_views_view_unformatted__produits_simialires(&$vars) {
  /**
   *
   * @var ViewExecutable $view
   */
  $view = $vars['view'];
  if ($view->current_display === 'block_3')
    foreach ($vars['rows'] as $key => $row) {
      if (isset($row['content']['#view_mode'])) {
        $template = _lesroidelareno_get_product_theme($vars['rows'][$key]['content']['#commerce_product']);
        $vars['rows'][$key]['content']['#view_mode'] = $template;
        $vars['rows'][$key]['content']['#cache']['keys'][3] = $template;
      }
    }
}

function _lesroidelareno_get_product_theme(Drupal\commerce_product\Entity\Product $product) {
  $val = $product->get('field_en_promotion_sur_les_roide')->offsetGet(0)->getValue();
  if (!empty($val['value'])) {
    return 'teaser_externe';
  }
  else {
    return 'teaser';
  }
}

/**
 * implement hook_ENTITY_TYPE_access
 */
function lesroidelareno_block_content_access(BlockContent $entity, $operation, AccountInterface $account) {
  if ($operation == 'update') {
    if ($entity->get('user_id')->target_id == $account->id())
      return AccessResult::allowed();
  }
}

/**
 * Implements hook_views_data_alter().
 */
function lesroidelareno_views_data_alter(array &$data) {
  /**
   * Ajout du filtre de domain pour les produits.
   * on identifie notre filtre avec 'product_field_domain_access'.
   * la colonne est definie : 'field'
   * la requete est cree par 'id'
   */
  if (!empty($data['commerce_product__field_domain_access'])) {
    // \Stephane888\Debug\debugLog::$max_depth = 7;
    // \Stephane888\Debug\debugLog::kintDebugDrupal($data['commerce_product__field_domain_access'],
    // 'lesroidelareno_views_data_alter', true);
    $data['commerce_product__field_domain_access']['product_field_domain_access'] = [
      'title' => t('Current domain'),
      'group' => t('Domain'),
      'filter' => [
        'field' => DomainAccessManagerInterface::DOMAIN_ACCESS_FIELD . '_target_id',
        'id' => 'lesroidelareno_domain_filter',
        'title' => t('Available on current domain'),
        'help' => t('Filters out nodes available on current domain ( published to current domain or all affiliates ).')
      ]
    ];
  }
  
  /**
   * Ajoute le filtre dans les resulats de recherches de search control.
   */
  if (!empty($data['search_api_index_produits']['field_domain_access'])) {
    $data['search_api_index_produits']['product_field_domain_access'] = [
      'title' => t('Current domain'),
      'group' => t('Domain'),
      'filter' => [
        'field' => DomainAccessManagerInterface::DOMAIN_ACCESS_FIELD,
        'id' => 'lesroidelareno_domain_filter',
        'title' => t('Available on current domain'),
        'help' => t('Filters out nodes available on current domain ( published to current domain or all affiliates ).')
      ]
    ];
  }
  
  /**
   * On ajoute le filtre pour les blocs personnalisé.
   */
  if (!empty($data['block_content__field_domain_access'])) {
    $data['block_content__field_domain_access']['product_field_domain_access'] = [
      'title' => t('Current domain'),
      'group' => t('Domain'),
      'filter' => [
        'field' => DomainAccessManagerInterface::DOMAIN_ACCESS_FIELD . '_target_id',
        'id' => 'lesroidelareno_domain_filter',
        'title' => t(' Available on current domain '),
        'help' => t(' Filters out nodes available on current domain ( published to current domain or all affiliates ). ')
      ]
    ];
  }
}

/**
 * implement hook_ENTITY_TYPE_access
 */
function lesroidelareno_domain_access(\Drupal\Core\Entity\EntityInterface $entity, $operation, AccountInterface $account) {
  if ($operation == 'view') {
    //
  }
}



